-- Initial Lekvo Book schema
CREATE TYPE "TransactionType" AS ENUM ('OPENING','CREDIT','PAYMENT','SALE','PURCHASE','EXPENSE','ADJUSTMENT');
CREATE TYPE "Direction" AS ENUM ('DEBIT','CREDIT');
CREATE TYPE "PaymentMethod" AS ENUM ('CASH','BANK_TRANSFER','UPI','CARD','GATEWAY');
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT','SENT','PARTIALLY_PAID','PAID','OVERDUE','CANCELLED');
CREATE TYPE "Role" AS ENUM ('OWNER','ADMIN','ACCOUNTANT','MANAGER','EMPLOYEE');
CREATE TYPE "OtpPurpose" AS ENUM ('SIGNUP','LOGIN','CHANGE_EMAIL','CHANGE_MOBILE');

CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"email" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"mobile" TEXT UNIQUE,"passwordHash" TEXT,"preferredLanguage" TEXT NOT NULL DEFAULT 'en',"emailVerifiedAt" TIMESTAMP(3),"mobileVerifiedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Business" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"phone" TEXT,"email" TEXT,"businessType" TEXT,"gstNumber" TEXT,"address" TEXT,"city" TEXT,"state" TEXT,"pincode" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "BusinessUser" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'EMPLOYEE',FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE,FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE,UNIQUE ("businessId","userId"));
CREATE TABLE "Customer" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"name" TEXT NOT NULL,"mobile" TEXT,"email" TEXT,"address" TEXT,"gstNumber" TEXT,"openingBalance" DECIMAL(65,30) NOT NULL DEFAULT 0,"creditLimit" DECIMAL(65,30) NOT NULL DEFAULT 0,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE);
CREATE TABLE "Supplier" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"name" TEXT NOT NULL,"mobile" TEXT,"email" TEXT,"address" TEXT,"gstNumber" TEXT,"openingBalance" DECIMAL(65,30) NOT NULL DEFAULT 0,"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE);
CREATE TABLE "LedgerTransaction" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"customerId" TEXT,"supplierId" TEXT,"type" "TransactionType" NOT NULL,"amount" DECIMAL(65,30) NOT NULL,"direction" "Direction" NOT NULL,"transactionDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdById" TEXT,"referenceNumber" TEXT,"notes" TEXT,"status" TEXT NOT NULL DEFAULT 'posted',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE,FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE,FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE CASCADE,FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL);
CREATE TABLE "Invoice" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"customerId" TEXT NOT NULL,"number" TEXT NOT NULL UNIQUE,"status" "InvoiceStatus" NOT NULL DEFAULT 'DRAFT',"subtotal" DECIMAL(65,30) NOT NULL DEFAULT 0,"tax" DECIMAL(65,30) NOT NULL DEFAULT 0,"discount" DECIMAL(65,30) NOT NULL DEFAULT 0,"total" DECIMAL(65,30) NOT NULL DEFAULT 0,"dueDate" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE);
CREATE TABLE "InvoiceItem" ("id" TEXT PRIMARY KEY,"invoiceId" TEXT NOT NULL,"description" TEXT NOT NULL,"quantity" DECIMAL(65,30) NOT NULL,"unitPrice" DECIMAL(65,30) NOT NULL,"taxRate" DECIMAL(65,30) NOT NULL DEFAULT 0,"total" DECIMAL(65,30) NOT NULL,FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE);
CREATE TABLE "Product" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"name" TEXT NOT NULL,"sku" TEXT,"category" TEXT,"unit" TEXT NOT NULL DEFAULT 'pcs',"purchasePrice" DECIMAL(65,30) NOT NULL DEFAULT 0,"sellingPrice" DECIMAL(65,30) NOT NULL DEFAULT 0,"openingStock" DECIMAL(65,30) NOT NULL DEFAULT 0,"lowStockThreshold" DECIMAL(65,30) NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE);
CREATE TABLE "Expense" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"category" TEXT NOT NULL,"amount" DECIMAL(65,30) NOT NULL,"date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"paymentMethod" "PaymentMethod" NOT NULL DEFAULT 'CASH',"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE);
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"businessId" TEXT,"userId" TEXT,"action" TEXT NOT NULL,"resource" TEXT NOT NULL,"resourceId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"metadata" JSONB);
CREATE TABLE "OtpChallenge" ("id" TEXT PRIMARY KEY,"identifier" TEXT NOT NULL,"channel" TEXT NOT NULL,"purpose" "OtpPurpose" NOT NULL,"codeHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"attempts" INTEGER NOT NULL DEFAULT 0,"verifiedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuthSession" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE);
CREATE TABLE "ApplicationSetting" ("id" TEXT PRIMARY KEY,"key" TEXT NOT NULL UNIQUE,"value" JSONB NOT NULL,"updatedById" TEXT,"updatedAt" TIMESTAMP(3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE SET NULL);
CREATE TABLE "NotificationProvider" ("id" TEXT PRIMARY KEY,"businessId" TEXT NOT NULL,"channel" TEXT NOT NULL,"provider" TEXT NOT NULL,"config" JSONB NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE);
CREATE TABLE "NotificationTemplate" ("id" TEXT PRIMARY KEY,"businessId" TEXT,"name" TEXT NOT NULL,"channel" TEXT NOT NULL,"subject" TEXT,"body" TEXT NOT NULL,"variables" JSONB,"enabled" BOOLEAN NOT NULL DEFAULT true);

CREATE INDEX "Customer_businessId_idx" ON "Customer"("businessId");
CREATE INDEX "Supplier_businessId_idx" ON "Supplier"("businessId");
CREATE INDEX "LedgerTransaction_businessId_transactionDate_idx" ON "LedgerTransaction"("businessId","transactionDate");
CREATE INDEX "LedgerTransaction_customerId_transactionDate_idx" ON "LedgerTransaction"("customerId","transactionDate");
CREATE INDEX "OtpChallenge_identifier_purpose_createdAt_idx" ON "OtpChallenge"("identifier","purpose","createdAt");
CREATE INDEX "AuthSession_userId_expiresAt_idx" ON "AuthSession"("userId","expiresAt");